Add retries & timeouts to CI steps. Split testing tool steps.

diff --git a/.github/workflows/nodejs.yml b/.github/workflows/nodejs.yml
--- a/.github/workflows/nodejs.yml
+++ b/.github/workflows/nodejs.yml
@@ -64,6 +64,7 @@ jobs:
       - name: npm ci
         run: npm ci
       - name: test-unit
+        timeout-minutes: 2
         run: npm run test-unit
 
   integration:
@@ -72,9 +73,6 @@ jobs:
     strategy:
       matrix:
         node-version: [12.x, 14.x]
-    env:
-      WEBSOCKET_URL: ws://localhost:8890/api/v1/ws
-
     steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v2
@@ -91,10 +89,18 @@ jobs:
           sudo service mysql stop
           sudo ifconfig docker0 10.200.10.1/24
           ${GITHUB_WORKSPACE}/streamr-dev/streamr-docker-dev/bin.sh start --wait
-      - name: test-integration
-        run: WEBSOCKET_URL=ws://localhost:8890/api/v1/ws DEBUG=Streamr* npm run test-integration -- --maxWorkers=1
-      - name: test-flakey
-        run: WEBSOCKET_URL=ws://localhost:8890/api/v1/ws npm run test-flakey || echo "::warning::Flakey Tests Failed" && true
+      - uses: nick-invision/retry@v2
+        id: test-integration
+        max_attempts: 3
+        timeout-minutes: 20
+        retry_on: error
+        command: WEBSOCKET_URL=ws://localhost:8890/api/v1/ws DEBUG=Streamr* npm run test-integration -- --maxWorkers=1
+      - uses: nick-invision/retry@v2
+        id: test-flakey
+        timeout-minutes: 20
+        max_attempts: 3
+        retry_on: error
+        command: WEBSOCKET_URL=ws://localhost:8890/api/v1/ws npm run test-flakey || echo "::warning::Flakey Tests Failed" && true
 
   browser:
     name: Test Browser using Node 14.x
@@ -121,6 +127,7 @@ jobs:
           sudo ifconfig docker0 10.200.10.1/24
           ${GITHUB_WORKSPACE}/streamr-dev/streamr-docker-dev/bin.sh start nginx broker-node-storage-1 broker-node-no-storage-1 broker-node-no-storage-2 engine-and-editor tracker-1 --wait
       - name: test-browser
+        timeout-minutes: 2
         run: WEBSOCKET_URL=ws://localhost:8890/api/v1/ws npm run test-browser
 
   benchmarks:
@@ -131,7 +138,6 @@ jobs:
     strategy:
       matrix:
         node-version: [12.x, 14.x]
-
     steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v2
@@ -141,8 +147,6 @@ jobs:
         with:
           name: build
           path: dist
-      - name: npm ci
-        run: npm ci
       - uses: actions/checkout@v2
         with:
           repository: streamr-dev/streamr-docker-dev
@@ -152,6 +156,8 @@ jobs:
           sudo service mysql stop
           sudo ifconfig docker0 10.200.10.1/24
           ${GITHUB_WORKSPACE}/streamr-dev/streamr-docker-dev/bin.sh start nginx broker-node-storage-1 broker-node-no-storage-1 broker-node-no-storage-2 engine-and-editor tracker-1 --wait
+      - name: npm ci
+        run: npm ci
       - name: benchmarks
         run: npm run benchmarks > benchmarks.txt
       - uses: actions/upload-artifact@v2
@@ -159,13 +165,11 @@ jobs:
           name: benchmarks
           path: benchmarks.txt
 
-      - name: test-flakey
-        continue-on-error: true
-        run: npm run test-flakey || echo "::warning::Flakey Tests Failed"
-
   streamr-client-testing-tool:
     needs: build
     runs-on: ubuntu-latest
+    env:
+        NUM_MESSAGES: 10
     steps:
       - uses: actions/checkout@v2
       - name: Use Node.js 14
@@ -180,16 +184,18 @@ jobs:
         with:
           repository: streamr-dev/streamr-docker-dev
           path: streamr-dev
-      - uses: actions/checkout@v2
-        with:
-          repository: streamr-dev/streamr-client-testing
-          path: streamr-client-testing
-      - name: setup
+      - name: setup-docker
         run: |
           sudo service mysql stop
           sudo ifconfig docker0 10.200.10.1/24
           ${GITHUB_WORKSPACE}/streamr-dev/streamr-docker-dev/bin.sh start nginx broker-node-storage-1 broker-node-no-storage-1 broker-node-no-storage-2 engine-and-editor tracker-1 --wait
-          cd ${GITHUB_WORKSPACE}/streamr-client-testing
+      - uses: actions/checkout@v2
+        with:
+          repository: streamr-dev/streamr-client-testing
+          path: streamr-client-testing
+      - name: setup-client-testing
+        working-directory: streamr-client-testing
+        run: |
           echo "Setup package.json to use PR JS client"
           sed -i "s/com.streamr:client:1.3.0/com.streamr:client:+/g" build.gradle
           sed -i "s/\"streamr-client\": \"\^3.1.2\"/\"streamr-client\":\"PATH\"/g" package.json
@@ -199,13 +205,23 @@ jobs:
           ## npm install is used because package-lock.json could be form a previous client version.
           npm install
           ./gradlew fatjar
-      - name: test
-        run: |
-          cd ${GITHUB_WORKSPACE}/streamr-client-testing
-          echo "Run streamr-client test"
-          java -jar build/libs/client_testing-1.0-SNAPSHOT.jar -s stream-cleartext-unsigned -n 10
-          java -jar build/libs/client_testing-1.0-SNAPSHOT.jar -s stream-cleartext-signed -n 10
-          java -jar build/libs/client_testing-1.0-SNAPSHOT.jar -s stream-encrypted-shared-signed -n 10
-          java -jar build/libs/client_testing-1.0-SNAPSHOT.jar -s stream-encrypted-shared-rotating-signed -n 10
-          java -jar build/libs/client_testing-1.0-SNAPSHOT.jar -s stream-encrypted-exchanged-rotating-signed -n 10
+      - name: stream-cleartext-unsigned
+        working-directory: streamr-client-testing
+        run: java -jar build/libs/client_testing-1.0-SNAPSHOT.jar -s stream-cleartext-unsigned -n $NUM_MESSAGES
+
+      - name: stream-cleartext-signed
+        working-directory: streamr-client-testing
+        run: java -jar build/libs/client_testing-1.0-SNAPSHOT.jar -s stream-cleartext-signed -n $NUM_MESSAGES
+
+      - name: stream-encrypted-shared-signed
+        working-directory: streamr-client-testing
+        run: java -jar build/libs/client_testing-1.0-SNAPSHOT.jar -s stream-encrypted-shared-signed -n $NUM_MESSAGES
+
+      - name: stream-encrypted-shared-rotating-signed
+        working-directory: streamr-client-testing
+        run: java -jar build/libs/client_testing-1.0-SNAPSHOT.jar -s stream-encrypted-shared-rotating-signed -n $NUM_MESSAGES
+
+      - name: stream-encrypted-exchanged-rotating-signed
+        working-directory: streamr-client-testing
+        run: java -jar build/libs/client_testing-1.0-SNAPSHOT.jar -s stream-encrypted-exchanged-rotating-signed -n $NUM_MESSAGES
 
